#ifndef DRONEMANAGER_GLOBAL_H
#define DRONEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRONEMANAGER_LIBRARY)
#  define DRONEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DRONEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DRONEMANAGER_GLOBAL_H
